workapp/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.BulletinHome.as_view(), name='bulletin_home'),
    path(
        'services/', views.PostListService.as_view(), name='bulletin_services'
        ),
    path(
        'requests/', views.PostListRequest.as_view(), name='bulletin_requests'
        ),
    path(
        '<slug:slug>/<slug:id>/', views.PostDetail.as_view(),
        name='post_detail'
        ),
]

workproject/urls.py
from django.contrib import admin
from django.urls import path, include
from workapp import views
from home import views as views_home

urlpatterns = [
    path('', views_home.HomePage.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('bulletin/', include('workapp.urls'), name='workapp_urls'),
    path('accounts/', include('allauth.urls')),
    path('profile/<slug:user>/', views.ProfilePage.as_view(), name='profile'),
    path('post_create/', views.PostCreate.as_view(), name='post_create'),
    path(
        'post_edit/<slug:post_id>/', views.PostEdit.as_view(), name='post_edit'
        ),
    path(
        'post_delete/<slug:post_id>/', views.PostDelete.as_view(),
        name='post_delete'
        ),
    path(
        'post_review_create/<slug:post_id>/', views.PostReviewCreate.as_view(),
        name='post_review_create'
        ),
]

workapp/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

POST_TYPE = ((0, "Service"), (1, "Request"))
PAYMENT_TYPE = ((0, "Per Hour"), (1, "Total Payment"))


class Post(models.Model):
    post_type = models.IntegerField(choices=POST_TYPE, default=0)
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=55)
    username = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user_posts"
        )
    updated_on = models.DateTimeField(auto_now=True)
    description = models.TextField(max_length=4000)
    featured_image = CloudinaryField('image', default='placeholder')
    blurb = models.TextField(blank=True, max_length=200)
    created_on = models.DateTimeField(auto_now_add=True)
    payment_type = models.IntegerField(choices=PAYMENT_TYPE, default=0)
    rate = models.PositiveIntegerField(default=0)
    contact_info = models.TextField(max_length=400)

    class Meta:
        # ordered in descending order, based on created_on value,
        # so that newest posts are first.
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def just_date_created_on(self):
        """Simplfies date"""
        return self.created_on.date()

    def just_date_updated_on(self):
        """Simplfies date"""
        return self.updated_on.date()

    def avg_rating(self):
        """Calculates the mean average rating of a post"""
        reviews = self.post_review.all()
        if len(reviews) > 0:
            review_total = 0
            for review in reviews:
                review_total += review.rating
            avg_rating_raw = (review_total)/(len(reviews))
            avg_rating = round(avg_rating_raw, 1)
            return avg_rating
        else:
            return 'N/A'

    def reviews_total(self):
        """Counts number of reviews a post has"""
        reviews = self.post_review.all()
        return len(reviews)


RATING = (
    (0, "0"),
    (0.5, "0.5"),
    (1, "1"),
    (1.5, "1.5"),
    (2, "2"),
    (2.5, "2.5"),
    (3, "3"),
    (3.5, "3.5"),
    (4, "4"),
    (4.5, "4.5"),
    (5, "5")
    )


class PostReview(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="post_review"
        )
    username = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user_review"
        )
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=55)
    updated_on = models.DateTimeField(auto_now=True)
    description = models.TextField(max_length=10000)
    created_on = models.DateTimeField(auto_now_add=True)
    rating = models.DecimalField(
        choices=RATING, max_digits=2, decimal_places=1
        )

    class Meta:
        # ordered in descending order, based on created_on value,
        # so that newest posts are first.
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def just_date_created_on(self):
        """Simplfies date"""
        return self.created_on.date()

    def just_date_updated_on(self):
        """Simplfies date"""
        return self.updated_on.date()

workapp/forms.py
from .models import Post, PostReview
from django import forms
from django.utils.translation import gettext_lazy as _
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from cloudinary.forms import CloudinaryFileField


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'post_type',
            'title',
            'description',
            'featured_image',
            'blurb',
            'payment_type',
            'rate',
            'contact_info',
        )
        labels = {
            'rate': _('Rate (€)'),
            'featured_image': _(
                'Featured Image (shown on the Bulletin Board. '
                'If no file uploaded, the default SideHustle '
                'image will be used)'
                ),
            'blurb': _('Blurb (max 200 characters)'),
            'contact_info': _(
                'Contact Info (how other users will contact '
                'you about your post)'
                )
        }
        widgets = {
            'description': SummernoteWidget(),
        }


class PostReviewForm(forms.ModelForm):
    class Meta:
        model = PostReview
        fields = (
                'title',
                'description',
                'rating',
            )

workapp/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic, View
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.contrib.auth.mixins import UserPassesTestMixin
from .models import Post, PostReview
from .forms import PostForm, PostReviewForm


class BulletinHome(generic.TemplateView):
    """View to show the bulletin home page"""
    template_name = 'workapp/bulletin_home.html'


class PostListService(generic.ListView):
    """View to show only service posts"""
    model = Post
    queryset = Post.objects.filter(post_type=0).order_by('-created_on')
    template_name = 'workapp/bulletin.html'
    paginate_by = 5


class PostListRequest(generic.ListView):
    """View to show only request posts"""
    model = Post
    queryset = Post.objects.filter(post_type=1).order_by('-created_on')
    template_name = 'workapp/bulletin.html'
    paginate_by = 5


class PostDetail(View):
    """View to show the details of a post"""
    def get(self, request, slug, id, *args, **kwargs):
        post = get_object_or_404(Post.objects, slug=slug, id=id)
        reviews = post.post_review.order_by('-created_on')
        if len(reviews) > 0:
            no_reviews = False
        else:
            no_reviews = True

        return render(
            request,
            'workapp/post_detail.html',
            {
                'post': post,
                'reviews': reviews,
                'no_reviews': no_reviews,
            },
        )


class PostCreate(UserPassesTestMixin, View):
    """View to handle post creation"""
    def get(self, request, *args, **kwargs):
        return render(
            request,
            'workapp/post_create.html',
            {
                'post_form': PostForm(),
            },
        )

    def post(self, request, *args, **kwargs):
        post_form = PostForm(request.POST, request.FILES)

        if post_form.is_valid():
            entry = post_form.save(commit=False)
            entry.username = request.user
            entry.slug = slugify(f'{entry.title}-{entry.username}')
            entry.save()
            post = get_object_or_404(Post.objects, id=entry.pk)

            return render(
                request,
                'workapp/post_create_success.html',
                {
                    'post': post,
                },
            )
        else:
            return render(
                request,
                'workapp/post_create.html',
                {
                    'post_form': PostForm(data=request.POST),
                },
            )

    def test_func(self):
        """Mixin Test"""
        return self.request.user.is_authenticated


class PostEdit(UserPassesTestMixin, View):
    """View to handle post editing"""
    def get(self, request, post_id, *args, **kwargs):
        post = get_object_or_404(Post.objects, id=post_id)
        if post.username == self.request.user:
            return render(
                request,
                'workapp/post_edit.html',
                {
                    'post_form': PostForm(instance=post),
                    'post': post,
                },
            )
        else:
            return render(
                request,
                '403.html',
            )

    def post(self, request, post_id, *args, **kwargs):
        post = get_object_or_404(Post.objects, id=post_id)
        post_form = PostForm(request.POST, request.FILES, instance=post)

        if post_form.is_valid():
            entry = post_form.save(commit=False)
            entry.username = request.user
            entry.slug = slugify(f'{entry.title}-{entry.username}')
            entry.save()

            return render(
                request,
                'workapp/post_edit_success.html',
                {
                    'post': post,
                },
            )

        else:
            return render(
                request,
                'workapp/post_edit.html',
                {
                    'post_form': PostForm(instance=post),
                    'post': post,
                },
            )

    def test_func(self):
        """Mixin Test"""
        return self.request.user.is_authenticated


class PostDelete(UserPassesTestMixin, View):
    """View to handle post deletion"""
    def get(self, request, post_id, *args, **kwargs):
        post = get_object_or_404(Post.objects, id=post_id)
        if post.username == self.request.user:
            user = post.username.pk
            post.delete()
            return render(
                        request,
                        'workapp/post_delete_success.html',
                        {
                            'user': user,
                        },
                    )
        else:
            return render(
                request,
                '403.html',
            )

    def test_func(self):
        """Mixin Test"""
        return self.request.user.is_authenticated


class ProfilePage(generic.ListView):
    """View to handle profile page display"""
    model = Post
    template_name = 'workapp/profile.html'
    pagenate_by = 10

    def get_queryset(self):
        """Gets only the posts the user in question has created"""
        return Post.objects.filter(username=self.kwargs.get('user'))


class PostReviewCreate(UserPassesTestMixin, View):
    """View to handle post review creation"""
    def get(self, request, post_id, *args, **kwargs):
        return render(
            request,
            'workapp/post_review_create.html',
            {
                'post_form': PostReviewForm(),
                'post_id': post_id
            },
        )

    def post(self, request, post_id, *args, **kwargs):
        post_form = PostReviewForm(request.POST)

        if post_form.is_valid():
            """If review form is valid, add review to database"""
            entry = post_form.save(commit=False)
            entry.username = request.user
            entry.slug = slugify(f'{entry.title}-{entry.username}')
            post = get_object_or_404(Post.objects, id=post_id)
            entry.post = post
            entry.save()

            return render(
                request,
                'workapp/post_review_create_success.html',
                {
                    'post': post,
                },
            )
        else:
            """If review form is not valid, return to form page"""
            return render(
                request,
                'workapp/post__review_create.html',
                {
                    'post_form': PostReviewForm(data=request.POST),
                },
            )

    def test_func(self):
        """Mixin Test"""
        return self.request.user.is_authenticated

workapp/templates/workapp/bulletin.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{% for post in post_list %}
{% if forloop.counter < 2 %}
Bulletin Board - {{ post.get_post_type_display }}s - Side Hustle
{% endif %}
{% endfor %}
{% endblock title %}

{% block content %}

{% for post in post_list %}
{% if forloop.counter < 2 %}
<div class="container text-center">
    <div>
        <h1 class="brand-h1">{{ post.get_post_type_display }}s</h1>
    </div>
</div>

{% endif %}
{% endfor %}

{% for post in post_list %}
<div class="container mt-4">
    <div class="card">
        <div class="card-header text-center">
            {{ post.get_post_type_display }}
        </div>
        <div class="row no-gutters">
            <div class="col-lg-4">
                <div class="card-body pb-0 p-lg-4 text-center">
                    {% if "placeholder" in post.featured_image.url %}
                    <a href="{% url 'post_detail' post.slug post.id %}">
                        <img class="rounded img-fluid border" src="https://res.cloudinary.com/dwjngety0/image/upload/v1682350889/full_logo_transparent3_gjakk2.png" alt="user's uploaded post image">
                    </a>
                    {% else %}
                    <a href="{% url 'post_detail' post.slug post.id %}">
                        <img class="rounded img-fluid border" src=" {{ post.featured_image.url }}" alt="website logo">
                    </a>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-8">
                <div class="card-body text-center text-lg-left pl-lg-0 pr-lg-4">
                    <a href="{% url 'post_detail' post.slug post.id %}">
                        <h2 class="card-title">{{ post.title }}</h2>
                    </a>
                    <p class="card-text">{{ post.blurb }}</p>
                    <p class="mb-1"><strong> Rating: {{ post.avg_rating }} <i class="fa-regular fa-star"></i></strong></p>
                    <p class="mt-0">Reviews: {{ post.reviews_total }}</p>
                </div>
            </div>
        </div>
        <div class="card-footer row no-gutters">
            <div class="col text-left">
                <a href="{% url 'profile' post.username.pk %}">{{ post.username }}</a>
            </div>
            <div class="col text-right">
                <p class="card-text text-muted h6">{{ post.just_date_created_on }}</p>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% if is_paginated %}
<nav aria-label="Page navigation" class="mt-4">
    <ul class="pagination justify-content-center mb-0">
        {% if page_obj.has_previous %}
        <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a>
        </li>
        {% else %}
        <li class="page-item disabled"><a class="page-link">&laquo; PREV </a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link"> NEXT &raquo;</a></li>
        {% endif %}
    </ul>
</nav>
{% endif %}

{%endblock%}

workapp/templates/workapp/bulletin_home.html
{% extends "base.html" %}
{% load static %}

{% block title %}Bulletin Board - Side Hustle{% endblock title %}

{% block content %}

<div class="container justify-content-center text-center">
    <h1 class="brand-h1 mx-4">Bulletin Board</h1>
    <div>
        <p class="mb-1">Services on offer</p>
        <a class=" btn btn-primary" href="{% url 'bulletin_services' %}">Services</a>
    </div>
    <div class="mt-4">
        <p class="mb-1">Requests for Services</p>
        <a class="btn btn-primary" href="{% url 'bulletin_requests' %}">Requests</a>
    </div>
    <div class="mt-4">
        <p class="mb-1 mx-2">Have a Service to offer, or want to make a Request of your own?</p>
        {% if user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'post_create' %}">Create Post</a>
        {% else %}
        <a class="btn btn-danger" href="{% url 'account_login' %}">Sign In to Create Post</a>
        {% endif %}
    </div>
</div>
{%endblock%}

workapp/templates/workapp/post_create.html
{% extends "base.html" %}

{% block title %}Create Post - Side Hustle{% endblock title %}

{% block content %}

{% load crispy_forms_tags %}
<div class="container">
    <form action="{% url 'post_create' %}" method="post" enctype='multipart/form-data'>
        {{ post_form | crispy | safe }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary mt-2">Create Post</button>
    </form>
</div>

{%endblock%}

workapp/templates/workapp/post_create_success.html
{% extends "base.html" %}

{% block title %}Post Success - Side Hustle{% endblock title %}

{% block content %}

<div class="container text-center">
    <div>
        <h1 class="brand-h1 mx-4">Post successfully created</h1>
    </div>
    <div class="mt-3">
        <a href="{% url 'post_detail' post.slug post.id %}" class="btn btn-primary">View Post</a>
    </div>
    <div class="p-3"></div>
    <div class="p-3"></div>
    <div class="mt-3">Posts can be edited/deleted from your Profile Page</div>
    <div class="mt-3">
        <a href="{% url 'profile' post.username.pk %}" class="btn btn-primary">View Profile</a>
    </div>
</div>

{%endblock%}

workapp/templates/workapp/post_delete_success.html
{% extends "base.html" %}

{% block title %}Post Success - Side Hustle{% endblock title %}

{% block content %}

<div class="container text-center">
    <div>
        <h1 class="brand-h1 mx-4">Post successfully deleted</h1>
    </div>
    <div class="mt-3">
        <a href="{% url 'profile' user %}" class="btn btn-primary">Profile Page</a>
    </div>
</div>

{%endblock%}

workapp/templates/workapp/post_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}Post - {{ post.username }} - {{ post.pk }} - Side Hustle{% endblock title %}

{% block content %}
<div class="container text-center" id="post-detail">
    <div class="card mt-0 mb-0">
        <div class="row no-gutters">
            <div class="col">
                <div class="card-header text-center">
                    <strong>Title</strong> 
                </div>
                <div class="card-body">
                    <h1>{{ post.title }}</h1>
                </div>
            </div>
        </div>
    </div>

    <div class="card mt-4">
        <div class="row no-gutters">
            <div class="col">
                <div class="card-body">
                    {% if "placeholder" in post.featured_image.url %}
                    <img class="rounded img-fluid border" src="https://res.cloudinary.com/dwjngety0/image/upload/v1682350889/full_logo_transparent3_gjakk2.png" alt="user's uploaded post image">
                    {% else %}
                    <img class="rounded img-fluid border" src=" {{ post.featured_image.url }}" alt="website logo">
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div class="card mt-4">
        <div class="row no-gutters">
            <div class="col">
                <div class="card-header text-center">
                    <strong>Blurb</strong> 
                </div>
                <div class="card-body">
                    {{ post.blurb | safe }}
                </div>
            </div>
        </div>
    </div>

    <div class="card mt-4">
        <div class="row no-gutters">
            <div class="col">
                <div class="card-header text-center">
                    <strong>Description</strong>
                </div>
                <div class="card-body">
                    {{ post.description | safe }}
                </div>
            </div>
        </div>
    </div>

    <div class="card mt-4">
        <div class="row no-gutters">
            <div class="col">
                <div class="card-header text-center">
                    <strong>Rate / Payment Type</strong>
                </div>
                <div class="card-body">
                    €{{ post.rate }} / {{ post.get_payment_type_display }}
                </div>
            </div>
        </div>
    </div>

    <div class="card mt-4">
        <div class="row no-gutters">
            <div class="col">
                <div class="card-header text-center">
                    <strong>Contact Information</strong>
                </div>
                {% if user.is_authenticated %}
                <div class="card-body">
                    <p>{{ post.contact_info }}</p>
                </div>
                {% else %}
                <div class="card-body">
                    <p>Sign In to view Contact Information</p>
                </div>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="card mt-4">
        <div class="row no-gutters">
            <div class="col">
                <div class="card-header text-center">
                    <strong>Profile Link</strong>
                </div>
                <div class="card-body">
                    <a href="{% url 'profile' post.username.pk %}">{{ post.username }}</a>
                </div>
            </div>
        </div>
    </div>

    <div class="card mt-4">
        <div class="row no-gutters">
            <div class="col">
                <div class="card-header text-center">
                    <strong>Post Created</strong>
                </div>
                <div class="card-body">
                    <p>{{ post.just_date_created_on }}</p>
                </div>
            </div>
        </div>
    </div>

    <div class="card mt-4">
        <div class="row no-gutters">
            <div class="col">
                <div class="card-header text-center">
                    <strong>Post Updated</strong>
                </div>
                <div class="card-body">
                    <p>{{ post.just_date_updated_on }}</p>
                </div>
            </div>
        </div>
    </div>

    <div class="reverse-bg rounded">
        <h2 class="brand-h1 mx-4 mt-4 reverse-bg">Reviews</h2>
    </div>
    <a href="{% url 'post_review_create' post.pk %}" class="btn btn-primary mt-3">Add Review</a>
    {% for review in reviews %}
    <div class="card mt-4">
        <div class="row no-gutters">
            <div class="col">
                <div class="card-body">
                    <p class="mb-2"><strong>{{ review.title }}</strong></p>
                    <p class="mb-2">{{ review.description }}</p>
                    <p><strong> Rating: {{ review.get_rating_display }} <i class="fa-regular fa-star"></i></strong></p>
                </div>
                <div class="card-footer row no-gutters">
                    <div class="col text-left">
                        <a class="card-text" href="{% url 'profile' review.username.pk %}">{{ review.username }}</a>
                    </div>
                    <div class="col text-right">
                        <p class="card-text text-muted h6">{{ review.just_date_created_on }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %} 
    {% if no_reviews %} 
    <div class="card mt-4">
        <div class="row no-gutters">
            <div class="col">
                <div class="card-body">
                    <p>No reviews for this post yet.</p>
                </div>
            </div>
        </div>
    </div>
    {% endif %}   
</div>
{%endblock%}

workapp/templates/workapp/post_edit.html
{% extends "base.html" %}

{% block title %}Edit Post - Side Hustle{% endblock title %}

{% block content %}

{% load crispy_forms_tags %}
<div class="container">
    <form action="{% url 'post_edit' post.pk %}" method="post" enctype='multipart/form-data'>
        {{ post_form | crispy | safe }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary mt-2">Update Post</button>
    </form>
</div>

{%endblock%}

workapp/templates/workapp/post_edit_success.html
{% extends "base.html" %}

{% block title %}Post Success - Side Hustle{% endblock title %}

{% block content %}

<div class="container text-center">
    <div>
        <h1 class="brand-h1 mx-4">Post successfully updated</h1>
    </div>
    <div class="mt-3">
        <a href="{% url 'post_detail' post.slug post.id %}" class="btn btn-primary">View Post</a>
    </div>
</div>

{%endblock%}

workapp/templates/workapp/post_review_create.html
{% extends "base.html" %}

{% block title %}Add Review - Side Hustle{% endblock title %}

{% block content %}

{% load crispy_forms_tags %}
<div class="container">
    <form action="{% url 'post_review_create' post_id %}" method="post">
        {{ post_form | crispy | safe }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary mt-2">Add Review</button>
    </form>
</div>

{%endblock%}

workapp/templates/workapp/post_review_create_success.html
{% extends "base.html" %}

{% block title %}Review Success - Side Hustle{% endblock title %}

{% block content %}

<div class="container text-center">
    <div>
        <h1 class="brand-h1 mx-4">Review successfully created</h1>
    </div>
    <div class="mt-3">
        <a href="{% url 'post_detail' post.slug post.id %}" class="btn btn-primary">View Reviewed Post</a>
    </div>
</div>

{%endblock%}

workapp/templates/workapp/profile.html
{% extends "base.html" %}
{% load static %}

{% block title %}

{% for post in post_list %}
{% if forloop.counter < 2 %}
Profile - {{ post.username }} - Side Hustle
{% endif %}
{% endfor %}

{% endblock title %}

{% block content %}

{% if post_list|length == 0 %}
<div class="container text-center">
    <div class="card mt-4">
        <div class="row no-gutters">
            <div class="col">
                <div class="card-body">
                    <p class="mb-1">No Posts created by user yet.</p>
                    <br>
                    <p class="mb-1">Profile Page shows all the posts that a user has created.</p>
                    <br>
                    If that user is signed in, they can edit/delete posts from their Profile Page.
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}

{% for post in post_list %}
{% if forloop.counter < 2 %}
<div class="container text-center">
    <div>
        <h1 class="brand-h1 mx-4">{{ post.username }}</h1>
    </div>
</div>
{% endif %}
{% endfor %}

{% for post in post_list %}
<div class="container mt-4">
    <div class="card">
        <div class="card-header text-center">
            {{ post.get_post_type_display }}
        </div>
        <div class="row no-gutters">
            <div class="col-lg-4">
                <div class="card-body pb-0 p-lg-4 text-center">
                    {% if "placeholder" in post.featured_image.url %}
                    <a href="{% url 'post_detail' post.slug post.id %}">
                        <img class="rounded img-fluid border" src="https://res.cloudinary.com/dwjngety0/image/upload/v1682350889/full_logo_transparent3_gjakk2.png"  alt="user's uploaded post image">
                    </a>
                    {% else %}
                    <a href="{% url 'post_detail' post.slug post.id %}">
                        <img class="rounded img-fluid border" src=" {{ post.featured_image.url }}" alt="website logo">
                    </a>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-8">
                <div class="card-body text-center text-lg-left pl-lg-0 pr-lg-4">
                    <a href="{% url 'post_detail' post.slug post.id %}">
                        <h2 class="card-title">{{ post.title }}</h2>
                    </a>
                    <p class="card-text">{{ post.blurb }}</p>
                    <p class="mb-1"><strong> Rating: {{ post.avg_rating }} <i class="fa-regular fa-star"></i></strong></p>
                    <p class="mt-0">Reviews: {{ post.reviews_total }}</p>
                </div>
            </div>
        </div>
        <div class="card-footer row no-gutters">
            <div class="col text-left">
                <a class="card-text" href="{% url 'profile' post.username.pk %}">{{ post.username }}</a>
            </div>
            <div class="col text-right">
                <p class="card-text text-muted h6">{{ post.just_date_created_on }}</p>
            </div>
        </div>
        {% if user.id is post.username.pk %}
        <div class="card-footer row no-gutters text-center">
            <div class="col text-right mx-2">
                <a class="btn btn-primary" href="{% url 'post_edit' post.pk %}">Edit Post</a>
            </div>
            <div class="col text-left mx-2">
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#confirmDelete{{ post.id }}">Delete Post</button>
            </div>
        </div>
        <!-- Modal -->
        <div class="modal fade" id="confirmDelete{{ post.id }}" tabindex="-1" aria-labelledby="confirmDelete{{ post.id }}Label" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header flex-column align-items-center">
                        <h5 class="modal-title" id="confirmDelete{{ post.id }}Label">Confirm Delete</h5>
                    </div>
                    <div class="modal-body text-center">
                        Are you sure you want to delete post?
                    </div>
                    <div class="modal-footer row text-center mr-0 ml-0">
                        <div class="col text-right mx-2 pr-0">
                            <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                        </div>
                        <div class="col text-left mx-2 pl-0">
                            <a class="btn btn-danger" href="{% url 'post_delete' post.pk %}">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
        {% endif %}
    </div>
</div>
{% endfor %}

{% if is_paginated %}
<nav aria-label="Page navigation" class="mt-4">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a>
        </li>
        {% else %}
        <li class="page-item disabled"><a class="page-link">&laquo; PREV </a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link"> NEXT &raquo;</a></li>
        {% endif %}
    </ul>
</nav>
{% endif %}

{%endblock%}